version: "3.7"
services:
  fakestack-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fakestack
  fakestack:
    image: fakestack
    depends_on:
      - fakestack-db
    environment:
      FAKESTACK_DB_USERNAME: postgres
      FAKESTACK_DB_PASSWORD: password
      FAKESTACK_DB_PORT: 5432
      FAKESTACK_DB_HOST: fakestack-db
      FAKESTACK_DB_DBNAME: fakestack
      FAKESTACK_DB_SSL_MODE: disable
      FAKESTACK_SERVER_PORT: 8080
    restart: unless-stopped
    ports: 
      - "8080:8080"
